name: Conan Build

on:
  workflow_call:
    inputs:
      platform:
        required: false
        default: 'ubuntu-24.04'
        type: string
      branch:
        required: true
        type: string
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string
      tooling:
        required: false
        type: string
        default: 'None'
      testing:
        required: false
        type: string
        default: 'False'
  workflow_dispatch:
    inputs:
      platform:
        required: true
        type: choice
        options:
          - ubuntu-24.04
        default: 'ubuntu-24.04'
      branch:
        required: true
        type: string
      build-type:
        required: true
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
      malloc-impl:
        description: 'Allocation Library'
        required: true
        type: choice
        options:
          - libc
          - tcmalloc
          - jemalloc
      prerelease:
        description: 'Fault Instrumentation'
        required: false
        type: choice
        options:
          - 'True'
          - 'False'
        default: 'False'
      tooling:
        required: false
        type: choice
          - 'Sanitize'
          - 'Coverage'
          - 'None'
        default: 'None'
      testing:
        description: 'Build and Run'
        required: true
        type: choice
        options:
          - 'True'
          - 'False'
        default: 'True'

jobs:
  BuildHomestoreDeps:
    runs-on: ${{ inputs.platform }}
    timeout-minutes: 1440
    steps:
    - name: Retrieve Code
      uses: actions/checkout@main
      with:
        ref: ${{ inputs.branch }}
      if: ${{ inputs.testing == 'True' }}

    - name: Retrieve Recipe
      uses: actions/checkout@main
      with:
        repository: eBay/Homestore
        ref: ${{ inputs.branch }}
      if: ${{ inputs.testing == 'False' }}

    - name: Setup Conan
      uses: ebay/sisl/.github/actions/setup_conan2@dev/v13.x
      with:
        platform: ${{ inputs.platform }}
      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Load Homestore Cache
      id: restore-cache
      uses: eBay/sisl/.github/actions/load_conan2@dev/v13.x
      with:
        testing: ${{ inputs.testing }}
        key_prefix: HomestoreDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}

    - name: Load Sisl Cache
      uses: eBay/sisl/.github/actions/load_conan2@dev/v13.x
      with:
        load_any: 'True'
        key_prefix: SislDeps13-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}
      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Retrieve Dependencies
      uses: actions/checkout@main
      with:
        repository: eBay/iomanager
        path: import/iomgr
        ref: dev/v12.x
      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Retrieve Dependencies
      uses: actions/checkout@main
      with:
        repository: eBay/nuraft_mesg
        path: import/nuraft_mesg
        ref: dev/v4.x
      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Load IOMgr Cache
      uses: eBay/sisl/.github/actions/load_conan2@dev/v13.x
      with:
        testing: 'False'
        path: import/iomgr
        key_prefix: IOMgrDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
        fail_on_cache_miss: true
      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Load NuraftMesg Cache
      uses: eBay/sisl/.github/actions/load_conan2@dev/v13.x
      with:
        testing: 'False'
        path: import/nuraft_mesg
        key_prefix: NuMesgDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}
        fail_on_cache_miss: true
      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Export Recipes
      run: |
        sudo apt-get install -y python3-pyelftools libaio-dev

        # make the following removed directory configurable, for example, using an environment variable.
        sudo rm -rf $ANDROID_HOME
        sudo rm -rf /usr/lib/llvm*
        sudo rm -rf /usr/lib/jvm
        sudo rm -rf /usr/lib/google-cloud-sdk
        
        python -m pip install pyelftools
        conan export --user oss --channel dev import/iomgr
        conan export --user oss --channel dev import/nuraft_mesg
      if: ${{ inputs.testing == 'True' || steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Build Cache
      run: |
        pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o iomgr/*:prerelease=${{ inputs.prerelease }}" || echo "")
        conan install \
            -c tools.build:skip_test=True \
            ${pre} \
            -o sisl/*:malloc_impl=${{ inputs.malloc-impl }} \
            -o iomgr/*:testing=off \
            -o homestore/*:testing=off \
            -s:h build_type=${{ inputs.build-type }} \
            -c tools.build:skip_test=True \
            --format=json \
            --build missing \
            . > ~/build.json
        conan list --graph ~/build.json --graph-binaries=build --format=json > ~/pkglist.json
      if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Save Conan Cache
      uses: eBay/sisl/.github/actions/store_conan2@dev/v13.x
      with:
        key_prefix: HomestoreDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
      if: ${{ github.event_name != 'pull_request' && steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Reload Sisl Cache
      uses: eBay/sisl/.github/actions/load_conan2@dev/v13.x
      with:
        load_any: 'True'
        key_prefix: SislDeps13-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}
      if: ${{ inputs.testing == 'True' && github.event_name != 'pull_request' && steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Reload IOMgr Cache
      uses: eBay/sisl/.github/actions/load_conan2@dev/v13.x
      with:
        testing: 'False'
        path: import/iomgr
        key_prefix: IOMgrDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}
        fail_on_cache_miss: true
      if: ${{ inputs.testing == 'True' && github.event_name != 'pull_request' && steps.restore-cache.outputs.cache-hit != 'true' }}

    - name: Reload NuraftMesg Cache
      uses: eBay/sisl/.github/actions/load_conan2@dev/v13.x
      with:
        testing: 'False'
        path: import/nuraft_mesg
        key_prefix: NuMesgDeps-${{ inputs.platform }}-${{ inputs.build-type }}-${{ inputs.malloc-impl }}
        fail_on_cache_miss: true
      if: ${{ inputs.testing == 'True' && github.event_name != 'pull_request' && steps.restore-cache.outputs.cache-hit != 'true' }}

    - uses: actions/checkout@main
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        detached: true
        connect-timeout-seconds: 60
      if: ${{ inputs.testing == 'True' }}

    - name: Create and Test Package
      run: |
        sanitize=$([[ "${{ inputs.tooling }}" == "Sanitize" ]] && echo "True" || echo "False")
        pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o iomgr/*:prerelease=${{ inputs.prerelease }}" || echo "")
        conan create \
            ${pre} \
            -o sisl/*:malloc_impl=${{ inputs.malloc-impl }} \
            -o iomgr/*:testing=off \
            -o homestore/*:sanitize=${sanitize} \
            -s:h build_type=${{ inputs.build-type }} \
            --build missing \
            .
      if: ${{ inputs.testing == 'True' && inputs.tooling != 'Coverage' }}

    - name: Code Coverage Run
      run: |
        pre=$([[ "${{ inputs.build-type }}" != "Debug" ]] && echo "-o iomgr/*:prerelease=${{ inputs.prerelease }}" || echo "")
        conan build \
            ${pre} \
            -o sisl/*:malloc_impl=${{ inputs.malloc-impl }} \
            -o iomgr/*:testing=off \
            -o homestore/*:coverage=True \
            -s:h build_type=${{ inputs.build-type }} \
            --build missing \
            .
      if: ${{ inputs.testing == 'True' && inputs.tooling == 'Coverage' }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
      if: ${{ inputs.testing == 'True' && inputs.tooling == 'Coverage' }}
