name: Build Commit

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string
      tooling:
        required: true
        type: string

jobs:
  SislDeps:
    uses: ebay/sisl/.github/workflows/build_dependencies.yml@dev/v13.x
    with:
      branch: dev/v13.x
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      tooling: None
    if: ${{ github.event_name != 'pull_request' }}

  NuraftMesgDeps:
    needs: SislDeps
    uses: eBay/nuraft_mesg/.github/workflows/build_dependencies.yml@dev/v4.x
    with:
      branch: dev/v4.x
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      tooling: None
    if: ${{ github.event_name != 'pull_request' }}

  IOMgrDeps:
    needs: SislDeps
    uses: eBay/iomanager/.github/workflows/build_dependencies.yml@dev/12.x
    with:
      branch: dev/12.x
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: None
    if: ${{ github.event_name != 'pull_request' }}

  HomestoreDeps:
    needs: [IOMgrDeps, NuraftMesgDeps]
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: ${{ github.ref }}
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: ${{ inputs.tooling }}
      testing: 'True'
    if: ${{ github.event_name != 'pull_request' }}

  HomestoreBuild:
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: ${{ github.ref }}
      platform: ${{ inputs.platform }}
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
      tooling: ${{ inputs.tooling }}
      testing: 'True'
    if: ${{ github.event_name == 'pull_request' }}
